version: '3.9'

#Volumes
volumes:
 wordpress:
  driver: local
  name: wordpress
  driver_opts:
   type: none
   o: bind
   device: /Users/jberegon/data/wp/
 db:
  driver: local
  name: database
  driver_opts:
   type: none
   o: bind
   device: /Users/jberegon/data/database/
 usr:
   driver: local
   name: usr
   driver_opts:
     type: none
     o: bind
     device: /Users/jberegon/data/usr/
networks:
  what_is_goin_on:
    name: what_is_goin_on
    driver: bridge

# Services
services:
  # Nginx Service
  nginx:
    ports:
      - "443:443"
    build: ./requirements/nginx/
    restart: always
    volumes:
      - ./requirements/nginx/tools/nginx-error.log:/var/log/nginx/error.log
      - ./requirements/nginx/tools/nginx-access.log:/var/log/nginx/access.log
      - wordpress:/var/www/html
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      - wordpress
#      wordpress:
#        condition: service_healthy
    container_name: nginx

  #WORD_PRESS
  wordpress:
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - wordpress:/var/www/html
      - usr:/usr/local/bin/
      - ./requirements/wordpress/tools/debug.log:/var/www/html/wordpress/wp-content/debug.log
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      - mariadb
#      mariadb:
#        condition: service_healthy
    healthcheck:
      test: -d /var/www/html/wordpress/
      interval: 5s
      retries: 10
    container_name: wordpress

  #MySQL Service
  mariadb:
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - ./requirements/mariadb/tools/error.log:/var/log/mysql/error.log
      - db:/var/lib/mysql
    env_file: .env
    networks:
      - what_is_goin_on
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u jberegon --password=dbpass
      interval: 5s
      retries: 10
    container_name: mariadb

  #REDIS_CACHE
#  redis_cache:
#    build: ./requirements/redis-cache/
#    restart: always
#    volumes:
#      - wordpress:/var/www/html
#      - usr:/usr/local/bin/
##      - ./requirements/redis-cache/conf/redis.conf:/etc/redis/redis.conf
#    env_file: .env
#    networks:
#      - what_is_goin_on
#    links:
#      - wordpress
#    depends_on:
#      - nginx
#    container_name: redis_cache


  ftpd-server:
    ports:
      - "2020:20"
      - "2021:21"
      - "12020:12020"
      - "12021:12021"
      - "12022:12022"
      - "12023:12023"
      - "12024:12024"
      - "12025:12025"
    build: ./requirements/vsftpd/
    restart: always
    volumes:
      - wordpress:/wp_ftp_content
    environment:
      USER: "user"
      PASS: "password"
    networks:
      - what_is_goin_on
#    depends_on:
#      - redis_cache
    container_name: ftpd-server

#  #Adminer
#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"
#    restart: always
#    environment:
#      ADMINER_DEFAULT_SERVER: mariadb
#    networks:
#      - what_is_goin_on
#    depends_on:
#      mariadb:
#        condition: service_healthy


