version: '3.9'

networks:
  what_is_goin_on:
    name: what_is_goin_on
    driver: bridge

# Services
services:

  # Nginx Service
  nginx:
    networks:
      - what_is_goin_on
    image: nginx:1.19
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./requirements/nginx/tools/nginx-error.log:/var/log/nginx/error.log
      - ./requirements/nginx/tools/nginx-access.log:/var/log/nginx/access.log
    depends_on:
      - wordpress
  #WORD_PRESS
  wordpress:
    networks:
      - what_is_goin_on
    image: wordpress:latest
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: demo
    depends_on:
      - mariadb
  # MySQL Service
  mariadb:
    networks:
      - what_is_goin_on
    image: mysql:8
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./requirements/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbdata:/var/lib/mysql
    restart: always
#    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
#      interval: 5s
#      retries: 10



  # Volumes
volumes:
  dbdata: