version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./requirements/php:/var/www/php
      - ./requirements/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    #    image: php:8.0-fpm
    build: ./requirements/php
    container_name: php
    working_dir: /var/www/php
    volumes:
      - ./requirements/php:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - wordpress

  # MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./requirements/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbdata:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      mysql:
        condition: service_healthy


  # Volumes
volumes:
  dbdata: