version: '3.9'

 #Volumes
volumes:
 wordpress:
  driver: local
  name: wordpress
  driver_opts:
   type: none
   o: bind
   device: /home/jberegon/data/wp
 db:
  driver: local
  name: db
  driver_opts:
   type: none
   o: bind
   device: /home/jberegon/data/database

networks:
  what_is_goin_on:
    name: what_is_goin_on
    driver: bridge

# Services
services:

  # Nginx Service
  nginx:
    networks:
      - what_is_goin_on
    image: nginx:1.19
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./requirements/nginx/tools/nginx-error.log:/var/log/nginx/error.log
      - ./requirements/nginx/tools/nginx-access.log:/var/log/nginx/access.log
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  #WORD_PRESS
  wordpress:
    networks:
      - what_is_goin_on
    image: wordpress:latest
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    volumes:
     - wordpress:/var/www/html
    env_file: .env
    depends_on:
      - mariadb
  # MySQL Service
  mariadb:
    networks:
      - what_is_goin_on
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - ./requirements/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - db:/var/lib/mysql
#    healthcheck:
#      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
#      interval: 5s
#      retries: 10