version: '3.9'

#Volumes
volumes:
 wordpress:
  driver: local
  name: wordpress
  driver_opts:
   type: none
   o: bind
   device: /Users/jberegon/data/html/
 db:
  driver: local
  name: database
  driver_opts:
   type: none
   o: bind
   device: /Users/jberegon/data/database/
 usr:
   driver: local
   name: usr
   driver_opts:
     type: none
     o: bind
     device: /Users/jberegon/data/usr/
 page:
   driver: local
   name: page
   driver_opts:
     type: none
     o: bind
     device: /Users/jberegon/data/page/
networks:
  what_is_goin_on:
    name: what_is_goin_on
    driver: bridge

# Services
services:
  # Nginx Service
  nginx:
    ports:
      - "443:443"
    build: ./requirements/nginx/
    restart: always
    volumes:
      - ./requirements/nginx/tools/nginx-error.log:/var/log/nginx/error.log
      - ./requirements/nginx/tools/nginx-access.log:/var/log/nginx/access.log
      - wordpress:/var/www/html/
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      - wordpress
    container_name: nginx
  #WORDPRESS
  wordpress:
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - wordpress:/var/www/html/
      - usr:/usr/local/bin/
      - ./requirements/wordpress/tools/debug.log:/var/www/html/wordpress/wp-content/debug.log
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      - mariadb
    container_name: wordpress
  #MySQL Service
  mariadb:
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - ./requirements/mariadb/tools/error.log:/var/log/mysql/error.log
      - db:/var/lib/mysql
    env_file: .env
    networks:
      - what_is_goin_on
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u jberegon --password=dbpass
      interval: 5s
      retries: 10
    container_name: mariadb
  #REDIS_CACHE
  redis_cache:
    build: ./requirements/bonus/redis-cache/
    restart: always
    volumes:
      - wordpress:/var/www/html/
      - usr:/usr/local/bin/
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      - nginx
    container_name: redis_cache
  #FTP
  ftpd-server:
    ports:
      - "2020:20"
      - "2021:21"
      - "12020:12020"
      - "12021:12021"
      - "12022:12022"
      - "12023:12023"
      - "12024:12024"
      - "12025:12025"
    build: ./requirements/bonus/vsftpd/
    restart: always
    volumes:
      - wordpress:/wp_ftp_content
    env_file: .env
    networks:
      - what_is_goin_on
    container_name: ftpd-server
  #Adminer
  adminer:
    build: ./requirements/bonus/adminer/
    restart: always
    volumes:
      - wordpress:/var/www/html/
    env_file: .env
    networks:
      - what_is_goin_on
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: adminer
  #HTML_PAGE
  page:
    build: ./requirements/bonus/my_page/
    restart: always
    volumes:
      - wordpress:/var/www/html/
    networks:
      - what_is_goin_on
    container_name: page
  #APACHE
  apache:
    ports:
      - "1443:443"
    build: ./requirements/bonus/apache/
    restart: always
    volumes:
      - ./requirements/bonus/apache/tools/logs/access.log:/var/log/apache2/access.log
      - ./requirements/bonus/apache/tools/logs/error.log:/var/log/apache2/error.log
    env_file: .env
    networks:
      - what_is_goin_on
    container_name: apache